### PR TITLE
implement a gradle plugin

### PR DESCRIPTION
**Pull request by BertrandA**
Address issue #15 by implemetings a gradle plugin with two tasks:

* **storkLauncher**: same as maven **stork-launcher** plugin except that it allow to define launchers directly into the gradle dsl
* **storkAssembly**: same as maven **stork-assembly** plugin

I tried to keep the usage as close as the maven plugin.
There is room for improvements, but I wanted to have some feedback's.

regards

### CODE REVIEW

**Comment by jjlauer** [comment]
@BertrandA Fantastic work!  Couple questions. 1) Can you actually define launchers in the gradle build file as well as `src/main/launchers` ?  If so that's super slick.  2) Since I release to maven central using the maven release plugin, I will need to make sure the gradle plugin gets released at the same time.  I haven't tried your code out yet, but where would this currently get published to?  In previous gradle plugin impls (e.g. in my fizzed/rocker project), we were able to get the Gradle plugin published to gradle's standard plugin repo.

**Comment by BertrandA** [comment]
Thanks a lot.

1) yes you can define a launcher directly in gradle dsl like this:
```
plugins {
    id 'java'
    id 'com.fizzed.stork'
}

storkLaunchers {
    launcher {
        name =  "test"
        displayName = "test"
        domain = "com.domain"
        shortDescription = "desc"
        type = "DAEMON"
        platforms = ["LINUX","MAC_OSX"]
        workingDirMode = "APP_HOME"
        mainClass="com.domain.MainClass"
    }
    launcher {
        name = "test2"
        [....]
    }
}
```
I will add more documentation on this feature.

2) I invoke the gradle build using **exec-maven-plugin** in the **prepare-package** phase, so maybe we can invoke the gradle publishing on the **deploy** phase

**Comment by jjlauer** [comment]
I did have some issues running tests & packaging, but I wanted to get this in the code base.  I'm going to comment out just a little bit of stuff since I need to do a new release, but hopefully we can tweak this a tad more and do another release soon.

**Comment by JamzTheMan** [comment]
Is this GA?  It looks like it's merged in but the readme still says "Gradle Plugin (to be released soon)"

Now that JDK11 has removed javapackager with no replacement date, I find something new...

**Pull request merged**
